# Generated by Django 6.0 on 2025-12-07 10:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Включить уведомления')),
                ('sound_notifications', models.BooleanField(default=True, verbose_name='Звуковые уведомления')),
                ('vibration_notifications', models.BooleanField(default=True, verbose_name='Вибрация')),
                ('notification_sound', models.CharField(choices=[('default', '🔔 По умолчанию'), ('soft', '🔕 Тихий'), ('brainrot', '🌀 BrainRot'), ('none', '🚫 Без звука')], default='default', max_length=50, verbose_name='Звук уведомлений')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Показывать статус онлайн')),
                ('show_last_seen', models.BooleanField(default=True, verbose_name="Показывать 'был(а) в сети'")),
                ('allow_typing_indicator', models.BooleanField(default=True, verbose_name="Показывать 'печатает...'")),
                ('save_media_automatically', models.BooleanField(default=False, verbose_name='Автосохранение медиа')),
                ('auto_delete_messages', models.IntegerField(choices=[(0, 'Никогда'), (86400, 'Через 24 часа'), (604800, 'Через 7 дней'), (2592000, 'Через 30 дней')], default=0, verbose_name='Автоудаление сообщений (секунды)')),
                ('theme', models.CharField(choices=[('light', '☀️ Светлая'), ('dark', '🌙 Темная'), ('brainrot', '🌀 BrainRot'), ('midnight', '🌌 Полночь')], default='light', max_length=20, verbose_name='Тема чата')),
                ('block_strangers', models.BooleanField(default=False, verbose_name='Блокировать незнакомцев')),
                ('require_verification', models.BooleanField(default=False, verbose_name='Требовать верификацию')),
                ('report_inappropriate', models.BooleanField(default=True, verbose_name='Сообщать о неприемлемом контенте')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Тихие часы: начало')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Тихие часы: конец')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки чата',
                'verbose_name_plural': 'Настройки чатов',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидание'), ('accepted', '✅ Принят'), ('rejected', '❌ Отклонен'), ('expired', '⏰ Истек')], default='pending', max_length=20, verbose_name='Статус мэтча')),
                ('match_type', models.CharField(choices=[('mutual_like', 'Взаимный лайк'), ('test_compatibility', 'Совместимость по тесту'), ('admin_generated', 'Создан администратором'), ('manual', 'Вручную')], default='mutual_like', max_length=50, verbose_name='Тип мэтча')),
                ('compatibility_score', models.FloatField(blank=True, help_text='От 0.0 до 1.0', null=True, verbose_name='Совместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Время мэтча')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('is_chat_active', models.BooleanField(default=True, verbose_name='Чат активен')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user_1', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user_2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2')),
            ],
            options={
                'verbose_name': 'Мэтч',
                'verbose_name_plural': 'Мэтчи',
                'ordering': ['-last_message_at', '-created_at'],
                'unique_together': {('user_1', 'user_2')},
            },
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate', 'Неприемлемый контент'), ('harassment', 'Домогательства'), ('spam', 'Спам'), ('fake_profile', 'Фейковый профиль'), ('underage', 'Несовершеннолетний'), ('other', 'Другое')], max_length=50, verbose_name='Тип жалобы')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='chat_reports/%Y/%m/%d/', verbose_name='Доказательства')),
                ('status', models.CharField(choices=[('pending', '⏳ На рассмотрении'), ('investigating', '🔍 Расследуется'), ('resolved', '✅ Решено'), ('dismissed', '❌ Отклонено')], default='pending', max_length=20, verbose_name='Статус жалобы')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('action_taken', models.TextField(blank=True, verbose_name='Принятые меры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решена')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='На кого жалуются')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Жалобщик')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.match', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Жалоба на чат',
                'verbose_name_plural': 'Жалобы на чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '📝 Текст'), ('image', '🖼️ Изображение'), ('video', '🎥 Видео'), ('audio', '🎵 Аудио'), ('sticker', '😺 Стикер'), ('system', '⚙️ Системное'), ('brainrot_gif', '🌀 BrainRot GIF')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('content', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='chat_media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm', 'mp3', 'wav'])], verbose_name='Медиа файл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/', verbose_name='Превью медиа')),
                ('is_brainrot_reaction', models.BooleanField(default=False, help_text='Сообщение является реакцией BrainRot', verbose_name='BrainRot реакция')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Редактировано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Редактировано в')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('brainrot_character', models.ForeignKey(blank=True, help_text='Персонаж, связанный с сообщением', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.brainrotcharacter', verbose_name='BrainRot персонаж')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.match', verbose_name='Мэтч')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠'), ('brainrot', '🌀'), ('fire', '🔥'), ('heart_eyes', '😍')], max_length=20, verbose_name='Тип реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', '🟢 Онлайн'), ('away', '🟡 Отошел'), ('busy', '🔴 Занят'), ('invisible', '⚫ Невидимка'), ('offline', '⚪ Оффлайн')], default='offline', max_length=20, verbose_name='Статус')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Был(а) в сети')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('is_typing', models.BooleanField(default=False, verbose_name='Печатает')),
                ('device_type', models.CharField(blank=True, choices=[('web', '🌐 Веб'), ('android', '🤖 Android'), ('ios', '🍎 iOS'), ('desktop', '💻 Десктоп')], max_length=50, verbose_name='Тип устройства')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='Версия приложения')),
                ('socket_id', models.CharField(blank=True, max_length=100, verbose_name='ID сокета')),
                ('connection_count', models.IntegerField(default=0, verbose_name='Количество соединений')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('current_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.match', verbose_name='Текущий чат')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус пользователя',
                'verbose_name_plural': 'Статусы пользователей',
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('block_type', models.CharField(choices=[('full', 'Полная блокировка'), ('messages_only', 'Только сообщения'), ('profile_only', 'Только профиль')], default='full', max_length=20, verbose_name='Тип блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заблокирован')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Кого блокируют')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='Кто блокирует')),
            ],
            options={
                'verbose_name': 'Блокировка чата',
                'verbose_name_plural': 'Блокировки чатов',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'sent_at'], name='chat_messag_match_i_c29638_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'sent_at'], name='chat_messag_sender__93ff77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user')},
        ),
    ]
