# Generated by Django 6.0 on 2025-12-07 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('category', models.CharField(choices=[('behavior', 'Поведение'), ('preferences', 'Предпочтения'), ('personality', 'Личность'), ('values', 'Ценности'), ('humor', 'Чувство юмора'), ('communication', 'Общение')], max_length=50, verbose_name='Категория')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('value', models.JSONField(help_text='JSON с весами для персонажей', verbose_name='Значение для алгоритма')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField(help_text='JSON с баллами для каждого персонажа', verbose_name='Баллы по персонажам')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.brainrotcharacter', verbose_name='Результат')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.CreateModel(
            name='CompatibilityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='От 0.0 до 1.0', verbose_name='Совместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание совместимости')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги совместимости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('character_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_first', to='characters.brainrotcharacter')),
                ('character_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_second', to='characters.brainrotcharacter')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Матрица совместимости',
                'unique_together': {('character_1', 'character_2')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swipe_type', models.CharField(choices=[('like', '❤️ Лайк'), ('dislike', '👎 Дизлайк'), ('super_like', '⭐ Суперлайк')], max_length=20, verbose_name='Тип свайпа')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='characters.brainrotcharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Свайп',
                'verbose_name_plural': 'Свайпы',
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'character')},
            },
        ),
    ]
