# Generated by Django 6.0 on 2025-12-07 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainRotCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название персонажа')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('category', models.CharField(choices=[('streamer', 'Стример/Блогер'), ('meme', 'Мемный персонаж'), ('game', 'Игровой персонаж'), ('movie', 'Кино/Сериал'), ('music', 'Музыкальный'), ('internet', 'Интернет-персонаж'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание персонажа')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='Происхождение')),
                ('year_emerged', models.IntegerField(blank=True, null=True, verbose_name='Год появления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brainrot_characters/', verbose_name='Изображение')),
                ('iconic_phrase', models.CharField(blank=True, max_length=200, verbose_name='Культовая фраза')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='Популярность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BrainRot персонаж',
                'verbose_name_plural': 'BrainRot персонажи',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название признака')),
                ('trait_type', models.CharField(choices=[('behavior', 'Поведение'), ('speech', 'Речь'), ('appearance', 'Внешность'), ('habit', 'Привычка'), ('reaction', 'Реакция'), ('preference', 'Предпочтение'), ('skill', 'Навык'), ('personality', 'Черта характера')], max_length=20, verbose_name='Тип признака')),
                ('description', models.TextField(verbose_name='Описание признака')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальный признак')),
                ('min_value', models.IntegerField(default=1, verbose_name='Минимальное значение')),
                ('max_value', models.IntegerField(default=10, verbose_name='Максимальное значение')),
                ('default_value', models.IntegerField(default=5, verbose_name='Значение по умолчанию')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='characters.brainrotcharacter', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Признак персонажа',
                'verbose_name_plural': 'Признаки персонажей',
                'ordering': ['trait_type', 'name'],
                'unique_together': {('name', 'character')},
            },
        ),
        migrations.CreateModel(
            name='UserCharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, verbose_name='Своё описание персонажа')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('show_in_search', models.BooleanField(default=True, verbose_name='Показывать в поиске')),
                ('character_level', models.IntegerField(default=1, verbose_name='Уровень персонажа')),
                ('xp_points', models.IntegerField(default=0, verbose_name='Очки опыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_characters', models.ManyToManyField(blank=True, related_name='secondary_users', to='characters.brainrotcharacter', verbose_name='Дополнительные персонажи')),
                ('main_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='characters.brainrotcharacter', verbose_name='Основной BrainRot персонаж')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brainrot_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль персонажа',
                'verbose_name_plural': 'Профили персонажей',
            },
        ),
        migrations.CreateModel(
            name='CustomTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название признака')),
                ('description', models.TextField(verbose_name='Описание')),
                ('trait_type', models.CharField(choices=[('behavior', 'Поведение'), ('speech', 'Речь'), ('appearance', 'Внешность'), ('habit', 'Привычка'), ('reaction', 'Реакция'), ('preference', 'Предпочтение'), ('skill', 'Навык'), ('personality', 'Черта характера')], max_length=20, verbose_name='Тип признака')),
                ('value', models.IntegerField(default=5, verbose_name='Значение')),
                ('max_value', models.IntegerField(default=10, verbose_name='Максимальное значение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный признак')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_traits', to='characters.usercharacterprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Кастомный признак',
                'verbose_name_plural': 'Кастомные признаки',
            },
        ),
        migrations.CreateModel(
            name='UserTraitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='Интенсивность признака от 1 до 10', verbose_name='Значение')),
                ('custom_note', models.TextField(blank=True, verbose_name='Примечание пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак активен')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_values', to='characters.charactertrait', verbose_name='Признак')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_values', to='characters.usercharacterprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Значение признака',
                'verbose_name_plural': 'Значения признаков',
                'unique_together': {('user_profile', 'trait')},
            },
        ),
    ]
